[package]
name = "testindex"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { version = "2.1.0", features = ["iterator", "stargate", "staking"] }
cw-storage-plus = "2.0.0"
schemars = "0.8.21"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }